// toggle side menu
export const SHOW_MENU = 'SHOW_MENU';
export const HIDE_MENU = 'HIDE_MENU';

// toggle modal
export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';

// save recent activity
export const SAVE_ACTIVITY_REQUEST = 'SAVE_ACTIVITY_REQUEST';
export const SAVE_ACTIVITY_SUCCESS = 'SAVE_ACTIVITY_SUCCESS';
export const SAVE_ACTIVITY_FAILURE = 'SAVE_ACTIVITY_FAILURE';

// get recent activity
export const GET_ACTIVITY_REQUEST = 'GET_ACTIVITY_REQUEST';
export const GET_ACTIVITY_SUCCESS = 'GET_ACTIVITY_SUCCESS';
export const GET_ACTIVITY_FAILURE = 'GET_ACTIVITY_FAILURE';

// fetch dummy emails
export const GET_EMAILS_REQUEST = 'GET_EMAILS_REQUEST';
export const GET_EMAILS_SUCCESS = 'GET_EMAILS_SUCCESS';
export const GET_EMAILS_FAILURE = 'GET_EMAILS_FAILURE';

// fetch transcripts
export const GET_TRANSCRIPTS_REQUEST = 'GET_TRANSCRIPTS_REQUEST';
export const GET_TRANSCRIPTS_SUCCESS = 'GET_TRANSCRIPTS_SUCCESS';
export const GET_TRANSCRIPTS_FAILURE = 'GET_TRANSCRIPTS_FAILURE';

// save transcripts
export const SAVE_TRANSCRIPT_REQUEST = 'SAVE_TRANSCRIPT_REQUEST';
export const SAVE_TRANSCRIPT_SUCCESS = 'SAVE_TRANSCRIPT_SUCCESS';
export const SAVE_TRANSCRIPT_FAILURE = 'SAVE_TRANSCRIPT_FAILURE';

// save new contact
export const SAVE_CONTACT_REQUEST = 'SAVE_CONTACT_REQUEST';
export const SAVE_CONTACT_SUCCESS = 'SAVE_CONTACT_SUCCESS';
export const SAVE_CONTACT_FAILURE = 'SAVE_CONTACT_FAILURE';

// get contacts
export const GET_CONTACTS_REQUEST = 'GET_CONTACTS_REQUEST';
export const GET_CONTACTS_SUCCESS = 'GET_CONTACTS_SUCCESS';
export const GET_CONTACTS_FAILURE = 'GET_CONTACTS_FAILURE';

// edit contact
export const EDIT_CONTACT_REQUEST = 'EDIT_CONTACT_REQUEST';
export const EDIT_CONTACT_SUCCESS = 'EDIT_CONTACT_SUCCESS';
export const EDIT_CONTACT_FAILURE = 'EDIT_CONTACT_FAILURE';

// delete contact
export const DELETE_CONTACT_REQUEST = 'DELETE_CONTACT_REQUEST';
export const DELETE_CONTACT_SUCCESS = 'DELETE_CONTACT_SUCCESS';
export const DELETE_CONTACT_FAILURE = 'DELETE_CONTACT_FAILURE';